version: "3"

services:
    mysql-hackersdb:
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./data:/project/data/
            - ./config/my.cnf:/etc/mysql/my.cnf
            - ./scripts/mysql:/docker-entrypoint-initdb.d
        ports:
            - "${MYSQL_PORT}:3306"
            
#    python-hackerrank:
#        build: .
#        volumes:
#            - ./target/data:/project/target/data
