version: "3"

services:
    hackerrank-mysql-db:
        image: mysql:8
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./data:/project/data/
            - ./config/my.cnf:/etc/mysql/my.cnf
            - ./scripts/mysql:/docker-entrypoint-initdb.d
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - hackerrank_network
           
    hackerrank-python-env:
        build:
            context: .
        volumes:
            - ./target/data:/project/target/data
        networks:
            - hackerrank_network
        depends_on:
            - hackerrank-mysql-db
        restart:
            on-failure

networks:
    hackerrank_network: 
        driver: bridge
